+define+ASIC_SYNTHESIS
+define+SYNTHESIS
+define+NDEBUG
+define+FPU_FPNEW
+define+EXT_F_ENABLE
+define+EXT_M_ENABLE
+define+ICACHE_ENABLE
+define+DCACHE_ENABLE
+define+LMEM_ENABLE
+define+NUM_CLUSTERS=1
+define+NUM_CORES=1
+define+NUM_WARPS=4
+define+NUM_THREADS=4
+incdir+/home/rid2/cs533.work/vortex/third_party/cvfpu/src
+incdir+/home/rid2/cs533.work/vortex/third_party/hardfloat/source
+incdir+/home/rid2/cs533.work/vortex/third_party/hardfloat/source/RISCV
+incdir+/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_pkg.sv
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/bsg_hardfloat_pkg.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_divsqrt_th_32.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_divsqrt_th_64_multi.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_opgroup_fmt_slice.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_rounding.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_top.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_fma.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_noncomp.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_cast_multi.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_opgroup_block.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_divsqrt_multi.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_classifier.sv
/home/rid2/cs533.work/vortex/third_party/cvfpu/src/fpnew_fma_multi.sv
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/mulRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/HardFloat_rawFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/divSqrtRecFN_small.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/HardFloat_primitives.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/compareRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/mulAddRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/isSigNaNRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/recFNToFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/divSqrtFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/divSqrtRecFN_medium.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/divSqrtRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/recFNToIN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/fNToRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/recFNToRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/addRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/iNToRecFN.v
/home/rid2/cs533.work/vortex/third_party/hardfloat/source/RISCV/HardFloat_specialize.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_64x128_1r1w.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_64x512_1rw.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_256x24_1r1w.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_64x24_1r1w.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_256x512_1rw.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_1024x32_1rw.v
/home/rid2/cs533.work/vortex/hw/syn/synopsys/libs/sram_128x128_1r1w.v
+incdir+/home/rid2/cs533.work/vortex/hw/rtl
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/interfaces
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/core
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/libs
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/fpu
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/mem
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/cache
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/tcu
+incdir+/home/rid2/cs533.work/vortex/hw/rtl/tcu/bhf
/home/rid2/cs533.work/vortex/hw/rtl/VX_gpu_pkg.sv
/home/rid2/cs533.work/vortex/hw/rtl/VX_trace_pkg.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_pkg.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_pkg.sv
/home/rid2/cs533.work/vortex/hw/rtl/Vortex.sv
/home/rid2/cs533.work/vortex/hw/rtl/VX_socket.sv
/home/rid2/cs533.work/vortex/hw/rtl/VX_cluster.sv
/home/rid2/cs533.work/vortex/hw/rtl/Vortex_axi.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_warp_ctl_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_result_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_decode_sched_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_writeback_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_dispatch_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_ibuffer_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_dcr_bus_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_sched_csr_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_decode_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_commit_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_schedule_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_execute_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_issue_sched_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_branch_ctl_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_fetch_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_commit_csr_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_scoreboard_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_operands_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/interfaces/VX_commit_sched_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_issue_slice.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_sfu_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_scoreboard.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_opc_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_alu_int.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_core.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_issue_top.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_schedule.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_uuid_gen.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_ibuffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_dispatch_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_wctl_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_dcr_data.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_csr_data.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_issue.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_lsu_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_mem_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_split_join.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_alu_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_fetch.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_mem_unit_top.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_gather_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_pe_switch.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_operands.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_ipdom_stack.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_commit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_uop_sequencer.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_core_top.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_execute.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_lsu_slice.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_csr_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_decode.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_dispatch.sv
/home/rid2/cs533.work/vortex/hw/rtl/core/VX_alu_muldiv.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_pack.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_demux.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_mux.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_unpack.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_scope_tap.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_bits_insert.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_allocator.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_pending_size.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_pipe_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_mem_coalescer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_skid_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_bypass_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_cyclic_arbiter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_elastic_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_mem_data_adapter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_placeholder.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_lzc.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_axi_adapter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_priority_arbiter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_avs_adapter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_serial_div.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_priority_encoder.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_ticket_lock.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_find_first.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_mem_bank_adapter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_scope_switch.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_async_ram_patch.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_xbar.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_divider.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_generic_arbiter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_serial_mul.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_sp_ram.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_shift_register.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_matrix_arbiter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_pe_serializer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_pipe_register.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_edge_trigger.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_dp_ram.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_popcount.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_multiplier.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_bits_remove.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_transpose.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_bits_concat.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_onehot_encoder.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_reset_relay.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_switch.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_reduce_tree.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_scan.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_nz_iterator.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_axi_write_ack.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_rr_arbiter.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_onehot_mux.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_mem_scheduler.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_index_queue.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_index_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_toggle_buffer.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_omega.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_onehot_shift.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_xpoint.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_stream_arb.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_fifo_queue.sv
/home/rid2/cs533.work/vortex/hw/rtl/libs/VX_elastic_adapter.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_csr_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_ncp.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fcvt_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fp_rounding.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fp_classifier.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_cvt.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_dpi.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_dsp.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fncp_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_sqrt.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_fma.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_div.sv
/home/rid2/cs533.work/vortex/hw/rtl/fpu/VX_fpu_fpnew.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_mem_arb.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_mem_switch.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_lsu_adapter.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_gbar_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_lsu_mem_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_lsu_mem_arb.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_gbar_bus_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_local_mem.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_local_mem_top.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_lmem_switch.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_gbar_arb.sv
/home/rid2/cs533.work/vortex/hw/rtl/mem/VX_mem_bus_if.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_tags.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_bypass.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_init.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_data.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_mshr.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_bank.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_wrap.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_cluster.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_repl.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_flush.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache.sv
/home/rid2/cs533.work/vortex/hw/rtl/cache/VX_cache_top.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_fedp_dpi.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_fedp_int.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_top.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_fedp_bhf.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_fp.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_unit.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_uops.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_fedp_dsp.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/VX_tcu_int.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/bhf/VX_tcu_bhf_bf16mul.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/bhf/bsg_counting_leading_zeros.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/bhf/VX_tcu_bhf_fmul.sv
/home/rid2/cs533.work/vortex/hw/rtl/tcu/bhf/VX_tcu_bhf_fadd.sv
