#!/usr/bin/env python3
"""
gen_floorplan_config.py — floorplan-budget section generator.

Reads `hw/pnr/cadence/config/<config>.toml` (hand-authored inputs),
resolves each hard-macro / IP entry against its LEF or Liberty file,
parses the DC stdcell area from the synthesis area report, applies the
halo-aware area-budget formula, and rewrites the `[budget]` section of
the same TOML in place (everything above the section header is preserved
verbatim). The TOML is the single source of truth — pnr.tcl reads it
directly via shared/toml_load.tcl.

Formula (basic profile, no effort tiers):

    A_macro_raw = sum_i  qty_i * W_i * H_i
    A_macro_eff = sum_i  qty_i * (W_i + 2*h_i) * (H_i + 2*h_i)
    A_stdcell   = DC report 'Total cell area'
    A_core      = A_macro_eff + A_stdcell / U_cell
    fp_h        = sqrt(A_core / aspect),  fp_w = fp_h * aspect
    U_overall   = (A_macro_raw + A_stdcell) / A_core    (warn if > 0.85)
"""

import argparse
import datetime
import os
import re
import sys
from pathlib import Path

import toml


AUTOGEN_HEADER = (
    "# [budget] is auto-generated by hw/scripts/gen_floorplan_config.py and\n"
    "# re-written on every `make <cfg>` invocation. Hand edits below this\n"
    "# line are discarded.\n"
)


_TOTAL_CELL_AREA_RE = re.compile(
    r'^\s*Total\s+cell\s+area\s*:\s*([\d.]+)\s*$', re.IGNORECASE
)
_MACRO_AREA_RE = re.compile(
    r'^\s*Macro/Black\s+Box\s+area\s*:\s*([\d.]+)\s*$', re.IGNORECASE
)
_LEF_SIZE_RE = re.compile(
    r'\bSIZE\s+([\d.]+)\s+BY\s+([\d.]+)\s*;', re.IGNORECASE
)
# NanGate45 stdcell SITE FreePDK45_38x28_10R_NP_162NW_34O is 0.19 × 1.4 µm.
# Die and core edges must land on multiples of these or Innovus auto-snaps
# (IMPFP-4026) and resizes (IMPFP-325). Hard-coded because the value is a
# property of the row/site, not the design.
SITE_W_UM = 0.19
SITE_H_UM = 1.4


def _snap_up(value, grid):
    """Round value UP to the next multiple of grid (keeps area >= request)."""
    import math
    return math.ceil(value / grid - 1e-9) * grid


def parse_dc_area_report(path):
    """Return stdcell-only area = 'Total cell area' − 'Macro/Black Box area'.

    DC's "Total cell area" lumps stdcells *and* macros. compute_budget()'s
    `a_eff` already covers macros (with halo), so adding the raw DC total to
    it would double-count the macro area — inflating the core by ~macro_area
    and leaving the stdcell region severely under-filled at placement.
    """
    total = None
    macros = 0.0  # Designs with no macros legitimately omit this line.
    with open(path, 'r', errors='replace') as fh:
        for line in fh:
            m = _TOTAL_CELL_AREA_RE.match(line)
            if m:
                total = float(m.group(1))
                continue
            m = _MACRO_AREA_RE.match(line)
            if m:
                macros = float(m.group(1))
    if total is None:
        raise ValueError(
            "'Total cell area' line not found in {}.\n"
            "Make sure it is the Design Compiler `report_area` output.".format(path)
        )
    return total - macros


def parse_lef_macro_size(path):
    with open(path, 'r', errors='replace') as fh:
        for line in fh:
            m = _LEF_SIZE_RE.search(line)
            if m:
                return float(m.group(1)), float(m.group(2))
    raise ValueError("SIZE statement not found in {}".format(path))


def parse_lib_cell_area(lib_path, cell_name):
    """Parse `area : <f>;` inside `cell (<name>) { ... }` block of a .lib."""
    cell_re = re.compile(
        r'cell\s*\(\s*' + re.escape(cell_name) + r'\s*\)\s*\{', re.IGNORECASE
    )
    area_re = re.compile(r'^\s*area\s*:\s*([\d.]+)\s*;', re.IGNORECASE)
    in_cell = False
    depth = 0
    with open(lib_path, 'r', errors='replace') as fh:
        for line in fh:
            if not in_cell:
                if cell_re.search(line):
                    in_cell = True
                    depth = line.count('{') - line.count('}')
                continue
            m = area_re.match(line)
            if m:
                return float(m.group(1))
            depth += line.count('{') - line.count('}')
            if depth <= 0:
                break
    raise ValueError(
        "area not found for cell '{}' in {}".format(cell_name, lib_path)
    )


def resolve_macro(entry, libs_dir):
    """
    Resolve a `[[macros]]` entry's footprint. Returns (W_um, H_um). The
    entry must carry an explicit lef_path (relative to libs_dir or absolute);
    the loader doesn't guess library layout.
    """
    name = entry['name']
    lef = entry.get('lef_path')
    if not lef:
        raise ValueError("macros[name={}] has no lef_path".format(name))
    if not os.path.isabs(lef):
        lef = os.path.normpath(os.path.join(libs_dir, lef))
    return parse_lef_macro_size(lef)


def compute_budget(cfg, config_name, libs_dir, syn_runs_dir):
    # Only [[macros]] entries with place != false count toward area.
    # Link-only entries (place = false) are loaded for routing context but
    # don't sit on this floor.
    macros = [m for m in cfg.get('macros', []) if m.get('place', True)]

    resolved = []
    a_raw = 0.0
    a_eff = 0.0
    for m in macros:
        if not m.get('name'):
            continue
        if 'count' not in m:
            raise ValueError("macros[name={}] is placed but has no count".format(m['name']))
        qty = int(m['count'])
        halo = float(m.get('halo_um', 0.0))
        w, h = resolve_macro(m, libs_dir)
        a_raw += qty * w * h
        a_eff += qty * (w + 2 * halo) * (h + 2 * halo)
        resolved.append({
            'name': m['name'], 'role': m.get('role', ''),
            'qty': qty, 'w_um': w, 'h_um': h, 'halo_um': halo,
            'single_raw_um2': w * h,
            'total_raw_um2': qty * w * h,
            'total_eff_um2': qty * (w + 2 * halo) * (h + 2 * halo),
        })

    area_rpt = os.path.join(syn_runs_dir, config_name, 'reports', 'area.rpt')
    if not os.path.isfile(area_rpt):
        raise FileNotFoundError(
            "DC area report not found: {}\n"
            "Run synthesis (hw/syn/synopsys) for config '{}' first.".format(area_rpt, config_name)
        )
    a_stdcell = parse_dc_area_report(area_rpt)

    fp = cfg.get('floorplan', {})
    u_cell = float(fp.get('target_utilization', 0.70))
    aspect = float(fp.get('aspect_ratio', 1.0))
    margin = float(fp.get('margin_um', 5.0))

    if not (0.1 <= u_cell <= 0.95):
        raise ValueError("target_utilization out of range: {}".format(u_cell))
    if aspect <= 0:
        raise ValueError("aspect_ratio must be > 0")

    a_core = a_eff + a_stdcell / u_cell
    core_h_raw = (a_core / aspect) ** 0.5
    core_w_raw = core_h_raw * aspect
    # Snap to the site grid so floorPlan -s L B R T lands flush on rows.
    margin_lr = _snap_up(margin, SITE_W_UM)
    margin_tb = _snap_up(margin, SITE_H_UM)
    core_w = _snap_up(core_w_raw, SITE_W_UM)
    core_h = _snap_up(core_h_raw, SITE_H_UM)
    # floorPlan -s takes DIE dims with core inset by margin per side.
    fp_h = core_h + 2 * margin_tb
    fp_w = core_w + 2 * margin_lr
    a_core = core_w * core_h
    u_overall = (a_raw + a_stdcell) / a_core if a_core > 0 else 0.0

    warnings = []
    if u_overall > 0.85:
        warnings.append(
            "u_overall={:.3f} exceeds 0.85 — consider lowering target_utilization "
            "or growing halos before committing the floorplan.".format(u_overall)
        )

    return {
        'config': config_name,
        'stdcell_area_um2': a_stdcell,
        'macro_area_raw_um2': a_raw,
        'macro_area_eff_um2': a_eff,
        'core_area_um2': a_core,
        'floorplan_w_um': fp_w,
        'floorplan_h_um': fp_h,
        'floorplan_margin_lr_um': margin_lr,
        'floorplan_margin_tb_um': margin_tb,
        'utilization_overall': u_overall,
        'target_utilization': u_cell,
        'aspect_ratio': aspect,
        'warnings': warnings,
        'resolved_macros': resolved,
        'area_report_path': area_rpt,
    }


def format_budget_toml(budget):
    """Render the `[budget]` section that gets appended to config.toml."""
    lines = ['[budget]']
    lines.append('generated_at        = "{}"'.format(
        datetime.datetime.now().isoformat(timespec='seconds')
    ))
    lines.append('stdcell_area_um2    = {:.3f}'.format(budget['stdcell_area_um2']))
    lines.append('macro_area_raw_um2  = {:.3f}'.format(budget['macro_area_raw_um2']))
    lines.append('macro_area_eff_um2  = {:.3f}'.format(budget['macro_area_eff_um2']))
    lines.append('core_area_um2       = {:.3f}'.format(budget['core_area_um2']))
    lines.append('floorplan_w_um         = {:.3f}'.format(budget['floorplan_w_um']))
    lines.append('floorplan_h_um         = {:.3f}'.format(budget['floorplan_h_um']))
    lines.append('floorplan_margin_lr_um = {:.3f}'.format(budget['floorplan_margin_lr_um']))
    lines.append('floorplan_margin_tb_um = {:.3f}'.format(budget['floorplan_margin_tb_um']))
    lines.append('utilization_overall    = {:.4f}'.format(budget['utilization_overall']))
    if budget['warnings']:
        lines.append('warnings = [')
        for w in budget['warnings']:
            lines.append('    "{}",'.format(w.replace('"', "'")))
        lines.append(']')
    else:
        lines.append('warnings = []')
    return '\n'.join(lines) + '\n'


def write_back_toml(toml_path, budget_section):
    """
    Strip the existing autogen-header + [budget] section (or any existing
    [budget] table) and rewrite both from scratch.
    """
    with open(toml_path, 'r') as fh:
        text = fh.read()

    if '# [budget] is auto-generated' in text:
        head = text.split('# [budget] is auto-generated')[0].rstrip() + '\n\n'
    elif '\n[budget]' in text:
        head = text.split('\n[budget]')[0].rstrip() + '\n\n'
    else:
        head = text.rstrip() + '\n\n'

    with open(toml_path, 'w') as fh:
        fh.write(head)
        fh.write(AUTOGEN_HEADER)
        fh.write(budget_section)


def print_report(cfg, budget):
    print()
    print('  ' + '─' * 78)
    print('  AREA BUDGET — {}'.format(budget['config']))
    print('  ' + '─' * 78)
    print('  area.rpt : {}'.format(budget['area_report_path']))
    print('  U_cell   : {:.0%}     aspect : {}'.format(
        budget['target_utilization'], budget['aspect_ratio']))
    print()
    print('  {:<22} {:>4}  {:>8}  {:>8}  {:>5}  {:>14}  {:>14}'.format(
        'NAME', 'QTY', 'W (µm)', 'H (µm)', 'HALO', 'RAW (µm²)', 'EFF (µm²)'))
    for r in budget['resolved_macros']:
        print('  {:<22} {:>4}  {:>8.3f}  {:>8.3f}  {:>5.1f}  {:>14,.2f}  {:>14,.2f}'.format(
            r['name'], r['qty'], r['w_um'], r['h_um'], r['halo_um'],
            r['total_raw_um2'], r['total_eff_um2']))
    print('  ' + '─' * 78)
    print('  Stdcell area      : {:>14,.2f} µm²'.format(budget['stdcell_area_um2']))
    print('  Macro area raw    : {:>14,.2f} µm²'.format(budget['macro_area_raw_um2']))
    print('  Macro area eff    : {:>14,.2f} µm²  (with halos)'.format(budget['macro_area_eff_um2']))
    print('  Stdcell / U_cell  : {:>14,.2f} µm²'.format(
        budget['stdcell_area_um2'] / budget['target_utilization']))
    print('  Core area         : {:>14,.2f} µm²'.format(budget['core_area_um2']))
    print('  Floorplan W × H   : {:>10.3f} × {:.3f} µm'.format(
        budget['floorplan_w_um'], budget['floorplan_h_um']))
    print('  Margin LR / TB    : {:>10.3f} / {:.3f} µm'.format(
        budget['floorplan_margin_lr_um'], budget['floorplan_margin_tb_um']))
    print('  U_overall         : {:.4f}'.format(budget['utilization_overall']))
    for w in budget['warnings']:
        print('  WARNING: {}'.format(w))
    print()


def main():
    here = Path(__file__).resolve().parent
    default_config_dir = (here / '..' / 'pnr' / 'cadence' / 'config').resolve()
    default_libs_dir = (here / '..' / 'syn' / 'synopsys' / 'libs').resolve()
    default_syn_runs = (here / '..' / 'syn' / 'synopsys' / 'runs').resolve()

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--config', required=True,
                    help='Configuration name, e.g. 2d-1c8s4w4t')
    ap.add_argument('--config_dir', default=str(default_config_dir),
                    help='Directory holding <config>.toml')
    ap.add_argument('--libs_dir', default=str(default_libs_dir),
                    help='hw/syn/synopsys/libs root')
    ap.add_argument('--syn_runs_dir', default=str(default_syn_runs),
                    help='hw/syn/synopsys/runs root (for area.rpt)')
    args = ap.parse_args()

    toml_path = Path(args.config_dir) / (args.config + '.toml')
    if not toml_path.is_file():
        sys.exit("ERROR: config toml not found: {}".format(toml_path))

    cfg = toml.load(str(toml_path))
    # Config name is derived from the filename — it's the contract the Makefile
    # uses (CONFIGS := $(notdir $(basename ...))). The TOML doesn't carry it.
    budget = compute_budget(cfg, args.config, args.libs_dir, args.syn_runs_dir)

    print_report(cfg, budget)

    write_back_toml(str(toml_path), format_budget_toml(budget))
    print('  Wrote: {}'.format(toml_path))


if __name__ == '__main__':
    main()
